#!/usr/bin/env bash
echo "Username: "
read username

if [[ -z "$username" ]]; then
username=$(whoami)
fi

echo "Password: "
read password

echo "Herhaal password: "
read password2

length=${#password}

while [[ $length < 8 ]] || [[ $password != $password2 ]]
do
echo "Password: "
read password

echo "Herhaal password: "
read password2

length=${#password}

done

echo -n "password : " >> $1
echo $password | md5sum >> $1
echo username : $username >> $1
