#!/usr/bin/env bash
for f in $(find ~/v1eos-practica/shell/bestanden -name *.jpg);
do convert "$f" -resize 128x128 "${f%.*}".png;
done
for f in $(find ~/v1eos-practica/shell/bestanden -name *.jpg);
do rm "$f";
done
