#!/usr/bin/env bash
mkdir ~/v1eos-practica/shell/bestanden/Afbeeldingen
for f in $(find ~/v1eos-practica/shell/bestanden -name *.jpg -or -name *.png);
do mv $f ~/v1eos-practica/shell/bestanden/Afbeeldingen; 
done
